### PR TITLE
Adds styles for `organisms-intro-hero`

### PR DESCRIPTION
**Pull request by kristianserrano**
This adds styles for the organisms-intro~fitted-hero pattern. See [emory-libraries/Pattern-Library#197](https://github.com/emory-libraries/Pattern-Library/issues/197)

### CODE REVIEW

**Review by laurenhamel — CHANGES_REQUESTED** [review]
@kristianserrano, after to reviewing the Figma designs again, I think this pattern more closely reflects the full hero intro design rather than the fitted hero intro one. When we were talking through some of this yesterday, I believe we ended up referencing the wrong page type: We were using the Services Directory page as a point of reference, but we should've been looking at the Cover page instead. The main difference between the full hero and fitted hero is that the full hero spans the entire page width whereas the fitted hero seems to respect the page's horizontal layout spacing.

This also leads me to another thought, since you seem to have mocked up a full hero pattern: I'm wondering if we should make the `organisms-intro-fitted-hero` component a bit more generic (something like `organisms-intro-hero`), then leverage the use of style modifier classes (i.e., `-fitted` vs. `-full`) to distinguish between the different hero intro types that we're designing?

**Comment by kristianserrano** [comment]
@laurenhamel regarding full-width vs. contained, wouldn't that be a factor of it being the full-width of the element in which it resides? I see it similarly to tiles which are inherently full-width until they are placed within the grid.

Additionally, the _only_ case I see in which it's not full-width is the Cover Page, and to be honest, I don't see why it shouldn't be.

**Comment by laurenhamel** [comment]
@kristianserrano, that's a fair assessment. I just want to make sure that we factor in, though, that at the page-level, we've mostly been assuming that all parts of the page are full-width, block-level elements (i.e., header, footer, main, major/minor sections, etc.) and not part of a grid, so under this assumption, and keeping with our current design approach, we've been trying to make all patterns self-contained (and using things like style modifiers to handle variations), which I think makes them a bit more scalable and atomic.

**Comment by kristianserrano** [comment]
@laurenhamel So to make sure I'm understanding you, you're saying we should add a variant class modifier that constrains the width and applies the layout spacing around the hero?

And what are your thoughts on making it full-width for the Cover page type to keep it consistent with other pages that include a hero?

**Comment by laurenhamel** [comment]
@kristianserrano, yes, I think if we keep the fitted hero style, we should utilize a variant class to apply the layout constraints. I wouldn't be opposed to eliminating the fitted style altogether, though, but would that be a question we'd want to raise with the rest of the team as well?

**Comment by kristianserrano** [comment]
@laurenhamel this is ready I think. There will be a merge conflict on `docs/index.html` but IIRC that's replaced altogether whenever it's generated, correct?

**Review by laurenhamel — APPROVED** [review]
This looks good. I went ahead and fixed the badge color issue and resolved conflicts. Approved.

**Pull request merged**
